<?xml version="1.0" ?>
<testsuite errors="1" failures="0" name="Test-20190805012750" tests="11" time="0.016">
	<testcase classname="Test" name="test_calcular_descuento_cliente_jovenes" time="0.002"/>
	<testcase classname="Test" name="test_calcular_descuento_clientes_generales" time="0.001"/>
	<testcase classname="Test" name="test_calcular_descuento_clientes_generales_valor_mayor_a_500" time="0.001"/>
	<testcase classname="Test" name="test_calcular_descuento_familias" time="0.001"/>
	<testcase classname="Test" name="test_calcular_descuento_familias_grandes" time="0.000"/>
	<testcase classname="Test" name="test_calcular_descuento_mayores_edad" time="0.001"/>
	<testcase classname="Test" name="test_calcular_descuento_mayores_edad_grandes_valores" time="0.001"/>
	<testcase classname="Test" name="test_calcular_descuento_no_valido" time="0.001"/>
	<testcase classname="Test" name="test_calcular_descuentos_especiales" time="0.000"/>
	<testcase classname="Test" name="test_nombre_casos_prueba" time="0.001"/>
	<testcase classname="Test" name="test_calcular_descuentos_especiales_altos_valores" time="0.007">
		<error message="'Descuento para familias' != 'Descuento especiales'
- Descuento para familias
+ Descuento especiales
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "test.py", line 37, in test_calcular_descuentos_especiales_altos_valores
    self.assertEqual(mensaje, 'Descuento especiales')
AssertionError: 'Descuento para familias' != 'Descuento especiales'
- Descuento para familias
+ Descuento especiales

]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
