<?xml version="1.0" ?>
<testsuite errors="1" failures="0" name="TestDescuentos-20190826084532" tests="9" time="0.007">
	<testcase classname="TestDescuentos" name="test_dependientes_invalidos" time="0.001"/>
	<testcase classname="TestDescuentos" name="test_edad_invalida" time="0.001"/>
	<testcase classname="TestDescuentos" name="test_validos_dos_dos" time="0.000"/>
	<testcase classname="TestDescuentos" name="test_validos_dos_uno_dos" time="0.001"/>
	<testcase classname="TestDescuentos" name="test_validos_dos_uno_uno" time="0.000"/>
	<testcase classname="TestDescuentos" name="test_validos_uno_dos" time="0.001"/>
	<testcase classname="TestDescuentos" name="test_validos_uno_uno" time="0.000"/>
	<testcase classname="TestDescuentos" name="test_valor_invalido" time="0.001"/>
	<testcase classname="TestDescuentos" name="test_validos_dos_tres" time="0.002">
		<error message="Tuples differ: ('No aplica', 0) != ('Descuento para familias', 180.00000000000003)

First differing element 0:
'No aplica'
'Descuento para familias'

- ('No aplica', 0)
+ ('Descuento para familias', 180.00000000000003)" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "test.py", line 93, in test_validos_dos_tres
    self.assertEqual(("No aplica", 0), retorno)
AssertionError: Tuples differ: ('No aplica', 0) != ('Descuento para familias', 180.00000000000003)

First differing element 0:
'No aplica'
'Descuento para familias'

- ('No aplica', 0)
+ ('Descuento para familias', 180.00000000000003)
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[('Descuento no valido', 0)
('Descuento no valido', 0)
('Descuento especiales', 420.0)
('Descuento para familias', 180.00000000000003)
('Descuento para familias', 60.0)
('Descuento para familias', 960.0)
('Descuento clientes iniciales', 156.0)
('Descuento clientes iniciales', 120.0)
('Descuento no valido', 0)
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
